### ISSUE TITLE
RenderPeople asset links and how to rig them

### ISSUE THREAD

**Issue by ggand0** [Unity-Technologies/PeopleSansPeople#18]
Thanks for sharing your awesome work.
In the paper, you state that PSP uses RenderPeople human models and added custom rigs to animate them. Could you provide the links to those assets? Would the models be simulation ready after applying animations with mixamo?

Section 3.1 in the paper:
> PEOPLESANSPEOPLE has a set of 28 scanned 3D human models from RenderPeople [36]. These
models are ethnically- and age-diverse, fully re-topologized, rigged, and skinned with high-quality
textures (Fig 2a). We added a character control rig to pose or animate them with motion capture data

**Comment by salehe-ee** [comment]
Thank you for your interest in this work.

In section 6 of the PeopleSansPeople paper we mention:

> We also provide a Unity template environment with example assets and full functionality of PeopleSansPeople. However, due to RenderPeople redistribution and licensing policies, we do not provide direct access to the 3D human assets; instead, we provide detailed instructions and examples for sourcing and making the human assets simulation-ready. 

Following the instructions on the paper, and the example assets we provided in the Unity template environment, you should be able to bring in any human assets into Unity and make them simulation ready.

**Comment by ggand0** [comment]
The unity env of this repo only includes the human assets you own, not all the models used to generate the actual dataset. I meant the URLs to the specific human assets you downloaded from RenderPeople to reproduce your work.

**Comment by salehe-ee** [comment]
As I mentioned in my comment above, for RenderPeople we do not own redistribution and licensing policies to allow us to send them to you. This includes redistributing links. You can look at the figures on the paper including [this one](https://github.com/Unity-Technologies/PeopleSansPeople/blob/main/images/shadergraph_renderpeople/renderpeople_material.png) to help you choose those assets from the RenderPeople library.

You must follow the same prefab setup as in the human prefab we have provided in the template Unity environment. We cannot know beforehand whether you need to modify the rigs or not, because the assets may have been sourced from anywhere. What's important is that you make them look like the one we have provided; i.e., set up the rig, randomizers, labelers, etc. such that your asset matches ours. Hope that is a good guideline for you.

**Comment by ggand0** [comment]
Thanks for your clarification. I see, you mean the "redistribution" includes giving out the URLs of assets. I'll manually try to look for similar assets in that case.

My second question is more of whether you applied special modifications to the RenderPeople models or their rigs with other tools than Unity. Did you only need to adjust settings within Unity / Unity Perception package to make animations work correctly? As RenderPeople models are not free, I was hoping to confirm this.

**Comment by salehe-ee** [comment]
You will need to adapt those assets to look exactly like the sample asset we have provided. Look under each provided asset, and also in the randomizers where those assets and their components are referenced.
If you want to do any clothing shader graph randomization, your materials, textures, albedos, and normals need to be separated for clothing.
You may or may not have to modify the rig too to ensure that the animation library you are going to be using can retarget well to your human assets.
